# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import name_service_pb2 as name__service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in name_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NameDirectoryServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Bind = channel.unary_unary(
                '/nameservice.NameDirectoryService/Bind',
                request_serializer=name__service__pb2.BindRequest.SerializeToString,
                response_deserializer=name__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Lookup = channel.unary_unary(
                '/nameservice.NameDirectoryService/Lookup',
                request_serializer=name__service__pb2.LookupRequest.SerializeToString,
                response_deserializer=name__service__pb2.AddressResponse.FromString,
                _registered_method=True)
        self.Unbind = channel.unary_unary(
                '/nameservice.NameDirectoryService/Unbind',
                request_serializer=name__service__pb2.UnbindRequest.SerializeToString,
                response_deserializer=name__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.RegisterType = channel.unary_unary(
                '/nameservice.NameDirectoryService/RegisterType',
                request_serializer=name__service__pb2.RegisterTypeRequest.SerializeToString,
                response_deserializer=name__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Discover = channel.unary_unary(
                '/nameservice.NameDirectoryService/Discover',
                request_serializer=name__service__pb2.DiscoverRequest.SerializeToString,
                response_deserializer=name__service__pb2.DiscoverResponse.FromString,
                _registered_method=True)


class NameDirectoryServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Bind(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Lookup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unbind(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Discover(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NameDirectoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Bind': grpc.unary_unary_rpc_method_handler(
                    servicer.Bind,
                    request_deserializer=name__service__pb2.BindRequest.FromString,
                    response_serializer=name__service__pb2.StatusResponse.SerializeToString,
            ),
            'Lookup': grpc.unary_unary_rpc_method_handler(
                    servicer.Lookup,
                    request_deserializer=name__service__pb2.LookupRequest.FromString,
                    response_serializer=name__service__pb2.AddressResponse.SerializeToString,
            ),
            'Unbind': grpc.unary_unary_rpc_method_handler(
                    servicer.Unbind,
                    request_deserializer=name__service__pb2.UnbindRequest.FromString,
                    response_serializer=name__service__pb2.StatusResponse.SerializeToString,
            ),
            'RegisterType': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterType,
                    request_deserializer=name__service__pb2.RegisterTypeRequest.FromString,
                    response_serializer=name__service__pb2.StatusResponse.SerializeToString,
            ),
            'Discover': grpc.unary_unary_rpc_method_handler(
                    servicer.Discover,
                    request_deserializer=name__service__pb2.DiscoverRequest.FromString,
                    response_serializer=name__service__pb2.DiscoverResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nameservice.NameDirectoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nameservice.NameDirectoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NameDirectoryService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Bind(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nameservice.NameDirectoryService/Bind',
            name__service__pb2.BindRequest.SerializeToString,
            name__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Lookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nameservice.NameDirectoryService/Lookup',
            name__service__pb2.LookupRequest.SerializeToString,
            name__service__pb2.AddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unbind(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nameservice.NameDirectoryService/Unbind',
            name__service__pb2.UnbindRequest.SerializeToString,
            name__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nameservice.NameDirectoryService/RegisterType',
            name__service__pb2.RegisterTypeRequest.SerializeToString,
            name__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Discover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nameservice.NameDirectoryService/Discover',
            name__service__pb2.DiscoverRequest.SerializeToString,
            name__service__pb2.DiscoverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
