# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: name_service.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'name_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12name_service.proto\x12\x0bnameservice\"#\n\x07\x41\x64\x64ress\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"B\n\x0b\x42indRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12%\n\x07\x61\x64\x64ress\x18\x02 \x01(\x0b\x32\x14.nameservice.Address\"\x1d\n\rLookupRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"`\n\x0f\x41\x64\x64ressResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12%\n\x07\x61\x64\x64ress\x18\x02 \x01(\x0b\x32\x14.nameservice.Address\x12\x15\n\rerror_message\x18\x03 \x01(\t\"\x1d\n\rUnbindRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"1\n\x13RegisterTypeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"8\n\x0eStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"\x1f\n\x0f\x44iscoverRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\"B\n\x0bProcessInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12%\n\x07\x61\x64\x64ress\x18\x02 \x01(\x0b\x32\x14.nameservice.Address\"?\n\x10\x44iscoverResponse\x12+\n\tprocesses\x18\x01 \x03(\x0b\x32\x18.nameservice.ProcessInfo2\xf4\x02\n\x14NameDirectoryService\x12=\n\x04\x42ind\x12\x18.nameservice.BindRequest\x1a\x1b.nameservice.StatusResponse\x12\x42\n\x06Lookup\x12\x1a.nameservice.LookupRequest\x1a\x1c.nameservice.AddressResponse\x12\x41\n\x06Unbind\x12\x1a.nameservice.UnbindRequest\x1a\x1b.nameservice.StatusResponse\x12M\n\x0cRegisterType\x12 .nameservice.RegisterTypeRequest\x1a\x1b.nameservice.StatusResponse\x12G\n\x08\x44iscover\x12\x1c.nameservice.DiscoverRequest\x1a\x1d.nameservice.DiscoverResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'name_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDRESS']._serialized_start=35
  _globals['_ADDRESS']._serialized_end=70
  _globals['_BINDREQUEST']._serialized_start=72
  _globals['_BINDREQUEST']._serialized_end=138
  _globals['_LOOKUPREQUEST']._serialized_start=140
  _globals['_LOOKUPREQUEST']._serialized_end=169
  _globals['_ADDRESSRESPONSE']._serialized_start=171
  _globals['_ADDRESSRESPONSE']._serialized_end=267
  _globals['_UNBINDREQUEST']._serialized_start=269
  _globals['_UNBINDREQUEST']._serialized_end=298
  _globals['_REGISTERTYPEREQUEST']._serialized_start=300
  _globals['_REGISTERTYPEREQUEST']._serialized_end=349
  _globals['_STATUSRESPONSE']._serialized_start=351
  _globals['_STATUSRESPONSE']._serialized_end=407
  _globals['_DISCOVERREQUEST']._serialized_start=409
  _globals['_DISCOVERREQUEST']._serialized_end=440
  _globals['_PROCESSINFO']._serialized_start=442
  _globals['_PROCESSINFO']._serialized_end=508
  _globals['_DISCOVERRESPONSE']._serialized_start=510
  _globals['_DISCOVERRESPONSE']._serialized_end=573
  _globals['_NAMEDIRECTORYSERVICE']._serialized_start=576
  _globals['_NAMEDIRECTORYSERVICE']._serialized_end=948
# @@protoc_insertion_point(module_scope)
